parameters:
#    d2bg_blog.example.class: D2bg\BlogBundle\Example
    webmaster: Denis BOUVIER GARZON
    
services:
#    d2bg_blog.example:
#        class: %d2bg_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
