parameters:
#    dbg_blog.example.class: Dbg\BlogBundle\Example

services:
#    dbg_blog.example:
#        class: %dbg_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
