<?php

namespace D2bg\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CiviliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiviliteRepository extends EntityRepository
{
}
