<?php

namespace Dbg\ProspectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * filiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filiereRepository extends EntityRepository
{
}
